pipeline {
    agent any

    // This creates the UI input box in Jenkins
    parameters {
        string(
            name: 'TARGET_URL',
            defaultValue: 'https://httpbin.test.k6.io/get',
            description: 'Enter the endpoint URL to run performance tests against'
        )
    }

    stages {
        stage('Execute k6 Load Test') {
            steps {
                echo "Running Performance Test against: ${params.TARGET_URL}"
                // Executes the test on your Windows machine, passing the URL
                bat "k6 run -e TARGET_URL=\"${params.TARGET_URL}\" scripts/url_load_test.js"
            }
        }
    }

    // This runs after the test finishes, regardless of pass/fail
    post {
        always {
            // Save the HTML report so you can download it from the Jenkins UI
            archiveArtifacts artifacts: 'reports/summary.html', fingerprint: true, allowEmptyArchive: false
            
            // Read the XML file to generate the Historical Trend Graph
            junit 'reports/junit.xml'
        }
    }
}